required: sudo

services:
  - docker 

before_install:
  - docker build -t rvettom/test-suite -f ./client/Dockerfile.dev ./client 
script:
  - docker run -e CI=true rvettom/test-suite npm run test
after_success:
  - docker build -t rvettom/multi-client ./client 
  - docker build -t rvettom/multi-nginx ./nginx
  - docker build -t rvettom/multi-server ./server
  - docker build -t rvettom/multi-worker ./worker
# Login to Docker via CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Push images to Dockerhum
  - docker push rvettom/multi-client
  - docker push rvettom/multi-nginx
  - docker push rvettom/multi-server
  - docker push rvettom/multi-worker 
deploy:
   provider: elasticbeanstalk
   region: "us-east-1"
   app: "docker-react"
   env: "DockerMulti-env"
   bucket_name: "elasticbeanstalk-us-east-1-803130306783"
   bucket_path: "docker-react"
   on:
     branch: master
   access_key_id: 
     secure: "$AWS_ACCESS_KEY"
   secret_access_key:
     secure: "$AWS_SECRET_KEY"
~                               
